### PR TITLE
Persistent Placeholder

### PR DESCRIPTION
**Pull request by IgorIlgiyaev**

### CODE REVIEW

**Review by moshe-moneytor — APPROVED** [review]

**Comment by MaxHammermann** [comment]
After updating to 2.1.2 including this PR, I get a

```
Uncaught TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (vuetify-google-autocomplete.common.js:1608:41)
    at eval (vuetify-google-autocomplete.common.js:1798:68)
    at eval (vuetify-google-autocomplete.common.js:7812:2)
    at eval (vuetify-google-autocomplete.common.js:7814:12)
    at ./node_modules/vuetify-google-autocomplete/dist/vuetify-google-autocomplete.common.js (chunk-vendors.js:7409:1)
    ```
